### ISSUE TITLE
How to solve the error about densitytool.f90 ？

### ISSUE THREAD

**Issue by Chenglp828** [llodeiro/DensityTool#7]
Thank you for providing such a good program. I have encountered a problem in the calculation process and need your help urgently. When running DOPCA, some PARCHG files can run normally, and some files have error prompts, such as PARCHG.0486.0001 prompts an error, but the adjacent band numbers PARCHG.0485.0001 and PARCHG.0487.0001 can be calculated. 

At line 207 of file DENSITYTOOL.F90 (unit = 12, file = 'PARCHG.0486.0001')
Fortran runtime error: Bad real number in item 14044038 of list input

Error termination. Backtrace:
#0  0x445170 in read_real
        at ../.././libgfortran/io/list_read.c:2026
#1  0x4473ec in list_formatted_read_scalar
        at ../.././libgfortran/io/list_read.c:2180
#2  0x412555 in ???
#3  0x42bcdc in ???
#4  0x467ac3 in ???
#5  0x400d50 in ???
Could you provide an input document (INCAR) for calculating PARCHG? Thank you very mach! Looking forward to your reply.

**Comment by llodeiro** [comment]
Hello,

This is a typical problem when a bunch of PARCHG files are printed, mainly
for systems with vacuum. It is not a problem of DensityTool as is, instead
is a problem in the VASP PARCHG file printing format, and it cannot be
fixed changing the INCAR file. The format problem trigger some number into
the matrix cannot be printed and instead ******** is printed. For that you
have to fix it manually. We usually put 0.000 at these points.... the error
related with this is pretty low/non-existent. For that, if you use a UNIX
terminal you can use the tips on the manual:
" Note that sometimes VASP writes *********** instead of the actual data,
leading to a reading error of DensityTool. Typically, this occurs only for
several data points and we thus recommend to set the values to 0.0. One can
find the PARCHG files in which this happens with:
    grep "\*\*\*\*\*\*\*\*\*\*\*" PARCHG.*
and substitute with:
     sed -i -e 's/\*\*\*\*\*\*\*\*\*\*\*/ 0.0000    /g' PARCHG.nnnn.kkkk
where PARCHG.nnnn.kkkk is the problematic file(s) identified with grep."

As said before this is not a problem of DensityTool, is a VASP problem, so
it is not related particularly with PCA routine... it can be appear in all
routines that use the PARCHG files directly, if the PARCHG files are not
corrected.

Regards - Lucas Lodeiro

**Comment by Chenglp828** [comment]
Thank you for your reply. The problem can be solved smoothly. Thanks again for your program. 
 Regards
Liping Cheng
