### ISSUE TITLE
Issue compiling with ifort v 18.0.1

### ISSUE THREAD

**Issue by eihernan** [llodeiro/DensityTool#8]
When I tried compiling with `ifort` on our campus compute cluster all of the STOP commands result in an error due to the use of a non-constant expression in the argument. Could you specify which versions of `ifort` or `gfortran` worked for compiling as is?

```
DENSITYTOOL.F90(240): error #6345: Either a PAUSE, STOP or ERROR STOP statement has an invalid argument.
      IF (OPEN_ERROR > 0) STOP 'An error occurred while creating the file '//TRIM(ONAME)//', the file already exists'
----------------------------------------------------------------------------------------^
```

I wanted to include the fix I used below in case anyone runs into this in the near future. The fix is simply to remove the variable from the error message which is of course less helpful than your original design.

`sed '/IF (OPEN_ERROR > 0) STOP/s/STOP .*/STOP "An IO error occurred."/' DENSITYTOOL.F90 > DensityTool.F90`

**Comment by llodeiro** [comment]
Hi

Currently we are using compilations with gfortran version 7.5.0 and 8.2.0
without problems. The problem with the change is the complete lost of
information w.r.t. which file is the problematic one. Also, the fix that
you mention needs more changes, for example do the same change in the caso
of TRIM(INAME), and probably more... I encourage to compile it using
gfortran so that it does not have compilation problems without loss of
features on the code.
Obviously you can make changes to the code if you want it.

Regards - Lucas

**Comment by eihernan** [comment]
Thank you for your reply.

I successfully compiled with gfortran version 12.2.0 now.

The fix above for the intel compiler does not need any changes. I compiled successfully with ifort v=18.0.1 before posting. I understand that it removes helpful error messages.

I recommend the README is updated to state the code is not compatible with intel compilers as written and to specify a minimum version of gfortran.

Thanks again!

**Comment by llodeiro** [comment]
Hi,
Happy to read you can compile it with gfortran without problems.

Thanks for your clarification, yes, your command line fixes all problems
with ifort. It changes the problematic //TRIM(INAME)// and //TRIM(ONAME)//
lines but also the no problematic ones when the EIGENVAL or CHGCAR are the
reading problem. But the thing is it fixes all and enables to compile with
ifort.

As you suggested, I added in the README file a caution paragraph about this
issue for future users.

Thanks and regards - Lucas Lodeiro
